### ISSUE TITLE
Freshness need to be moved under config

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/snowflake_dbt_partner_demo#53]
In the source file `src_jaffle_shop.yml` we have [freshness as a top level property](https://github.com/dbt-labs/snowflake_dbt_partner_demo/blob/084ab6d02f88669a858767671c170a1a691ecc76/models/staging/jaffle_shop/src_jaffle_shop.yml#L19). It should be moved under a config property.

That is to say that the following

```
      - name: orders
        identifier: orders
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after:
            count: 12
            period: hour
          error_after:
            count: 24
            period: hour
```

should become 

```
      - name: orders
        identifier: orders
        loaded_at_field: _etl_loaded_at
        config:
          freshness:
            warn_after:
              count: 12
              period: hour
            error_after:
              count: 24
              period: hour
```
